name: daymemory
description: Day memory - Private Journal

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.14+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  equatable: ^2.0.5
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  
  video_player_web: ^2.0.16
  wakelock_web: ^0.4.0
  flutter_inappwebview: ^5.7.2+3
  flutter_html: ^3.0.0-beta.2
  flutter_quill: ^7.4.1
  vsc_quill_delta_to_html: ^1.0.3
  #delta_markdown: ^0.8.0
  tuple: ^2.0.2
  retry: ^3.1.2

  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  get_it: ^7.6.0
  pull_to_refresh_flutter3: ^2.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6

  flutter_slidable: ^3.0.0
  confirm_dialog: ^1.0.2
  keyboard_actions: ^4.2.0
  shared_preferences: ^2.2.0
  settings_ui: ^2.0.2
  flutter_local_notifications: ^15.1.0+1
  flutter_staggered_grid_view: ^0.7.0

  local_auth: ^2.1.6
  flutter_fgbg: ^0.3.0
  secure_application: ^3.8.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  image_picker: ^1.0.2
  image_picker_windows: ^0.2.1
  flutter_image_compress: ^2.0.4

  fluent_ui: ^4.7.3
  window_manager: ^0.3.5
  flutter_acrylic: ^1.1.3
  system_theme: ^2.3.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1

  url_strategy: ^0.2.0
  url_launcher: ^6.1.12
  clipboard: ^0.1.3

  #flutter_facebook_auth: ^5.0.7
  flutter_facebook_auth: ^6.0.1
  #flutter_facebook_auth: ^5.0.0-dev.1
  google_sign_in: ^6.1.4
  google_sign_in_ios: ^5.6.2
  sign_in_with_apple: ^5.0.0
  # flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^10.5.0
  html: ^0.15.4

  drift: ^2.11.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.0
  path: ^1.8.2

  flutter_redux: ^0.10.0
  built_collection: ^5.1.1
  built_value: ^8.6.1
  flutter_jailbreak_detection: ^1.10.0
  device_info_plus: ^9.0.3
  flutter_svg: ^2.0.7
  connectivity_plus: ^4.0.2
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.4.3
  flutter_dotenv: ^5.1.0
  hexcolor: ^3.0.1
  
  devicelocale: ^0.6.0
  package_info_plus: ^4.1.0
  page_view_indicators: ^2.0.0
  styled_text: ^8.1.0
  uuid: ^3.0.7
  #scrolls_to_top: ^2.1.0
  scrolls_to_top:
    git:
      url: https://github.com/changweihua/scrolls_to_top.git
      ref: 5d15e145734a375f6deb717e65a6aa3220da7545
  image: ^4.0.17
  flutter_easyloading: ^3.0.5
  firebase_crashlytics: ^3.3.5
  modal_bottom_sheet: ^3.0.0-pre
  photo_view: ^0.14.0
  #wakelock: ^0.6.2
  wakelock_plus: ^1.1.1
  encrypt: ^5.0.1
  jiffy: ^6.2.1
  mixpanel_flutter: ^2.1.1

  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  video_compress: ^3.1.2
  dart_vlc: ^0.4.0
  #ffmpeg_kit_flutter: ^5.1.0

  

dependency_overrides:
  analyzer: ^5.2.0
  i18n_extension: ^9.0.2
  
  
  

dev_dependencies:
  drift_dev: ^2.2.0+1
  build_runner: ^2.4.6
  built_value_generator: ^8.6.2
  flutter_native_splash: ^2.3.2
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  msix: ^3.16.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - env/  
    - assets/    
    - assets/png/
    - assets/svg/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: MuseoSans
    fonts:
      - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_100.ttf
        weight: 100
      - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_300.ttf
        weight: 300
      - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_500.ttf
        weight: 500
      - asset: assets/fonts/MuseoSans/Museo_Sans_Cyrl_700.ttf
        weight: 700

msix_config:
  display_name: Day Memory
  publisher_display_name: Day Memory
  identity_name: net.daymemory
  msix_version: 1.0.0.3
  logo_path: [path to logo]
  capabilities: internetClient, location, microphone, webcam
  debug: false
  trim_logo: false
  languages: en-US,uk-UA
  build_windows: false